### ISSUE TITLE
This plugin suppose sdkman installed under ~/.sdkman

### ISSUE THREAD

**Issue by liaoya** [deather/omf-sdk#1]
Would you please take a look at https://github.com/derekstavis/plugin-nvm, can it read the location of sdkman via SDKMAN_DIR

**Comment by deather** [comment]
Hi @liaoya ,

Yes you're right, it is a bad idea to suppose that. I correct it.

Thanks for submitting

**Comment by andriy-rudyk** [comment]
I added ` set -x SDKMAN_DIR "/Users/username/.sdkman"` to my `.config/fish/conf.d/omf.fish` file. But now every time I open a new shell I get:
`bash: line 0: source: filename argument required
source: usage: source filename [arguments]`

Any ideas?
