### ISSUE TITLE
sdk command hangs

### ISSUE THREAD

**Issue by benkonz** [deather/omf-sdk#10]
Hi, not sure if this is a SDKMAN issue or a omf-sdk issue, but whenever I try to run a `sdk COMMAND` command, the program hangs. (even `sdk --version`), not sure what changed on my system, as I haven't updated sdkman, and it was working for a while, but suddenly it hangs on all the commands I run with it

**Comment by deather** [comment]
Hi,

I tried this morning, and I effectively have this problem a short time. Now it seems to work. The last changes concerns the completion of command, so it must not be a problem.

Can you recheck please to confirm it is always the case ?

**Comment by benkonz** [comment]
Hi, yeah, I uninstalled `omf-sdk`, `sdkman`, and removed the `~/.sdkman` directory, reinstalled everything, and it looks like it's working now

**Comment by deather** [comment]
Ok it is curious. Thanks for the feedback.
