### ISSUE TITLE
Overriding SDKMAN_DIR not working

### ISSUE THREAD

**Issue by deather** [deather/omf-sdk#2]
I added ` set -x SDKMAN_DIR "/Users/username/.sdkman"` to my `.config/fish/conf.d/omf.fish` file. But now every time I open a new shell I get:

`bash: line 0: source: filename argument required
source: usage: source filename [arguments]`

Any ideas?

_Originally posted by @andriy-rudyk in https://github.com/deather/omf-sdk/issues/1#issuecomment-441771377_

**Comment by deather** [comment]
@andriy-rudyk Can you test the fix for me ? I'm not a macos user. I want to know if it fixes for this OS.

Thanks for reporting

**Comment by andriy-rudyk** [comment]
Just removed and installed the plugin again, now I get a bit different error:
`Last login: Tue Nov 27 09:57:42 on ttys004 bash: /bin/sdkman-init.sh: No such file or directory`

**Comment by deather** [comment]
@andriy-rudyk I hope this fix will be good. :crossed_fingers:

**Comment by andriy-rudyk** [comment]
```Last login: Tue Nov 27 11:12:42 on ttys000
bash: /bin/sdkman-init.sh: No such file or directory
Darwin arudy-mb15tbr 18.2.0 x86_64
11:13  up 12 days,  2:14, 4 users, load averages: 1.43 1.67 1.97
 ~  sdk list java                                                               Tue Nov 27 11:13:19 2018
bash: /bin/sdkman-init.sh: No such file or directory
 !  ~ ```

**Comment by andriy-rudyk** [comment]
looks like I can do it manually:
```
~/.s/bin  set -g hello $SDKMAN_DIR                    Tue Nov 27 11:18:25 2018
 ~/.s/bin  echo $hello                                 Tue Nov 27 11:18:40 2018
/Users/andriy.rudyk/.sdkman
 ~/.s/bin  fenv "source $hello/bin/sdkman-init.sh"     Tue Nov 27 11:18:46 2018
 ~/.s/bin  sdk list java                       166ms  Tue Nov 27 11:20:31 2018
================================================================================
Available Java Versions
================================================================================
     12.ea.20-open
     11.0.1-zulu
     11.0.1-open
     10.0.2-zulu
     10.0.2-open
     9.0.7-zulu
     9.0.4-open
     8.0.192-zulu
 > * 8.0.191-oracle
   * 7.0.181-zulu
     1.0.0-rc9-graal
     1.0.0-rc8-graal
     1.0.0-rc7-graal



================================================================================
```

**Comment by andriy-rudyk** [comment]
The weird thing is this only happens when I change my default shell from zsh to fish and open a new window. If I fire up fish from zsh, everything works fine. As soon as I `chsh`, open new window things are broken

**Comment by deather** [comment]
This is weird. Have you tried to echo $SDKMAN_DIR ? I have the sensation that fish don't set/export this variable, because the filepath printed in the error, missing the SDKMAN_DIR.

**Comment by andriy-rudyk** [comment]
It returns the correct path. Maybe it's being set after something is trying to use it? So at the time the plugin references it it's not yet set? Right now I'm setting it inside: `.config/fish/conf.d/omf.fish` Ideas?

**Comment by deather** [comment]
Yes thats it. I think it is the call of `source $OMF_PATH/init.fish` which loading the packages. I think it is better to set SDKMAN_PATH in the file `.config/fish/config.fish`.

**Comment by andriy-rudyk** [comment]
Setting SDKMAN path in `.config/fish/config.fish` didn't work, what what did the trick was setting it inside: `~/.config/omf/before.init.fish`as per https://github.com/oh-my-fish/oh-my-fish#advanced
Everything seems to work fine now, thanks for all the help, maybe add:
`set -g SDKMAN_DIR "/Users/username/.sdkman"` inside `~/.config/omf/before.init.fish` to the README if you get a chance?

**Comment by deather** [comment]
Thank you for all. I think it is better to add a file in directory `.config/fish/conf.d`, because if you want to remove the usage of omf, you need to restore the variables in `~/.config/omf/before.init.fish` in the `conf.d` directory.
