### ISSUE TITLE
Completion bug - sdk use

### ISSUE THREAD

**Issue by dbottstein** [deather/omf-sdk#9]
complete -c sdk -f -n '__fish_sdkman_using_command use' -a "(__fish_sdkman_candidates)"
complete -c sdk -f -n '__fish_sdkman_specifying_candidate use' -a "(__fish_sdkman_installed_versions)"

Enter

`sdk use <tab>`

Completion presents a list of all candidates. Select a candidate that is not installed and complete again for version.

`sdk use activemq <tab>`

The call to __fish_sdkman_installed_versions results in an error.

`ls: /Users/don/.local/share/sdkman/candidates/activemq: No such file or directory`

The first completion should present a list of installed candidates only.

**Comment by deather** [comment]
Did you have installed any version of activemq ?
